# Generated by Django 4.2.23 on 2025-07-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_user_address_user_email_user_interested_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
