# Generated by Django 4.2.23 on 2025-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_opinion_poll_readeropinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('news', 'News'), ('sport', 'Sports'), ('science', 'Science'), ('technology', 'Technology'), ('bussiness', 'bussiness')], default='', max_length=30)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='no_votes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='yes_votes',
            field=models.IntegerField(),
        ),
    ]
