# Generated by Django 4.2.23 on 2025-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0005_video_alter_poll_no_votes_alter_poll_yes_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('entertainment', 'Entertainment'), ('sport', 'Sports'), ('science', 'Science'), ('bussiness', 'bussiness'), ('news', 'News')], default='', max_length=30),
        ),
    ]
